#page title
page_title                                : Blog Site                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_title                                 : Mustafa Bayer Blog
app_name                                  : Yenilikçi Verimli Servis ve Mobil Uygulamalar   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Android & IOS & Web App                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : React Native / Reactjs / Graphql / Apollo / Spring Framework.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Mustafa Bayer                                
your_link                                 : https://mustafabayer.com                     
your_city                                 : Istanbul                  
email_address                             : an80x86@gmail.com
facebook_username                         :                                           
instagram_username                        : usacalabayer
twitter_username                          : an80x86
github_username                           : an80x86
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : React Native
    description                           : Native React, Facebook tarafından oluşturulan açık kaynaklı bir mobil uygulama çerçevesidir. Geliştiricilerin yerel platform yetenekleriyle birlikte React'i kullanmalarını sağlayarak Android, iOS ve UWP için uygulamalar geliştirmek için kullanılır
    fontawesome_icon_name                 : star
    
  - title                                 : ReactJS 
    description                           : ReactJS, ya da React.js, kullanıcı arayüzü oluşturmaya yarayan açık kaynak kodlu web uygulama çatısı. Facebook önderliğinde bir geliştirici grubu tarafından geliştirilmekte olan ReactJS, Model-View-Controller prensibine uygun olarak oluşturulmuştur.
    fontawesome_icon_name                 : star

  - title                                 : Redux
    description                           : Redux, uygulama durumunu yönetmek için açık kaynaklı bir JavaScript kütüphanesidir. En çok kullanıcı arayüzleri oluşturmak için React veya Angular gibi kütüphanelerle kullanılır. Facebook'un Flux mimarisine benzer şekilde Dan Abramov ve Andrew Clark tarafından geliştirilmiştir.
    fontawesome_icon_name                 : star

  - title                                 : GraphQL
    description                           : GraphQL, API'ler için açık kaynaklı bir veri sorgusu ve manipülasyon dili ve mevcut verilerle sorguların yerine getirilmesi için bir çalışma zamanıdır. GraphQL, 2012 yılında halka açılmadan önce 2012 yılında Facebook tarafından dahili olarak geliştirilmiştir.
    fontawesome_icon_name                 : star

  - title                                 : Apollo Graphql
    description                           : GraphQL'i ölçekte çalıştırmanız gereken tüm devtol ve bulut hizmetleriyle eski API'lerin yama çalışmasını değiştirmek için tek bir çok yönlü sorgu sistemi.
    fontawesome_icon_name                 : star
  
  - title                                 : Spring Framework
    description                           : Spring Framework Java ve .NET için geliştirilmiş, açık kaynak olan bir uygulama geliştirme çatısıdır. Spring Framework'ün temel özellikleri harhangi bir Java uygulaması tarafından kullanılabilmektedir. Eklentileri ile birlikte Java Enterprise platform üzerinde web uygulamaları geliştirmek için de kullanılabilir.
    fontawesome_icon_name                 : star

  - title                                 : Amazon Web Service
    description                           : AWS, peşin harcama veya uzun vadeli taahhüt gerekmeksizin düşük, kullandıkça öde fiyatlandırma seçenekleri sunar. Uygun ölçekte küresel bir altyapı oluşturur.
    fontawesome_icon_name                 : star

  - title                                 : Aws Lambda
    description                           : AWS Lambda, Amazon tarafından Amazon İnternet Hizmetlerinin bir parçası olarak sağlanan, olaya dayalı, sunucusuz bir bilgi işlem platformudur. Olaylara yanıt olarak kod çalıştıran ve bu kodun gerektirdiği bilgi işlem kaynaklarını otomatik olarak yöneten bir bilgisayar hizmetidir.
    fontawesome_icon_name                 : star

  - title                                 : Amazon DynamoDB
    description                           : Dinamo birlikte yüksek oranda kullanılabilir anahtar-değer yapılı bir depolama sistemi veya dağıtılmış bir veri deposu oluşturabilen bir teknikler kümesidir. Her iki veritabanının ve dağıtılmış karma tabloların özelliklerine sahiptir.
    fontawesome_icon_name                 : star

  - title                                 : MongoDB
    description                           : MongoDB Inc. tarafından ölçeklenebilir, doküman tabanlı, C++ ile geliştirilmiş açık kaynak, NoSQL veritabanı uygulamasıdır. MongoDB, verileri JSON tipinde dokümanlarda saklamakatadır, anlamsal alanları dokümandan dokümana değişir ve veri yapısı zaman içinde değiştirilebilir.
    fontawesome_icon_name                 : star

  - title                                 : PostgreSQL
    description                           : PostgreSQL, veritabanları için ilişkisel modeli kullanan ve SQL standart sorgu dilini destekleyen bir veritabanı yönetim sistemidir. PostgreSQL aynı zamanda iyi performans veren, güvenli ve geniş özellikleri olan bir Veri Tabanı Yönetim Sistemi'dir. Hemen hemen tüm UNIX ya da Unix türevi işletim sistemlerinde çalışır.
    fontawesome_icon_name                 : star

  - title                                 : Kubernetes
    description                           : Kubernet'ler, uygulama dağıtımını, ölçeklendirmeyi ve yönetimi otomatikleştirmek için açık kaynaklı bir konteyner düzenleme sistemidir.
    fontawesome_icon_name                 : star



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8
logome_image                              : assets/me.jpg
logo1_image                               : assets/react.png
logo2_image                               : assets/apollo.png
logo3_image                               : assets/spring.png

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
